### ISSUE TITLE
need a (MISSED TIME/Need Manual Time) button

### ISSUE THREAD

**Issue by GoogleCodeExporter** [amayers1/ww-canoe-kayak-slalom#11]
```
1.  When timing equipment fails to pick up a time, need ability to mark an 
entry as needing manual time

```

Original issue reported on code.google.com by `allen.ma...@gmail.com` on 23 Nov 2014 at 9:10

**Comment by amayers1** [comment]
Resolved, an "Adjust Time" button now appears on the timing screen.  It allows selections of race run times in most recently finished order.  The time can be adjusted manually from keyboard.  Adjustment of time is limited to the current run.
