### ISSUE TITLE
Enhancement Implement ICF Gate Judge diagram and penalty assessments  

### ISSUE THREAD

**Issue by GoogleCodeExporter** [amayers1/ww-canoe-kayak-slalom#5]
```
Branch name:trunk

Purpose of code changes on this branch:Implement ICF requirements for 
national/international races


When reviewing my code changes, please focus on:functionality UXD


After the review, I'll merge this branch into:
/trunk


```

Original issue reported on code.google.com by `allen.ma...@gmail.com` on 7 Nov 2013 at 10:05

Attachments:
* [ICFPenaltyDiagram.png](https://storage.googleapis.com/google-code-attachments/ww-canoe-kayak-slalom/issue-5/comment-0/ICFPenaltyDiagram.png)
* [ICFPenaltyLegend.png](https://storage.googleapis.com/google-code-attachments/ww-canoe-kayak-slalom/issue-5/comment-0/ICFPenaltyLegend.png)

**Comment by amayers1** [comment]
This has been implemented, although the solution is not elegant.
